# <center>Classification Problem</center>
## Import Panda and Numpy Library

In [3]:
# Import the libraries
import numpy as np
import pandas as pd

## Load The DataSet From The Local Directory

In [4]:
# Import the Dataset using pandas
Train = pd.read_csv(r'Train_data_classification.csv') # path
Test = pd.read_csv(r'Test_data_classification.csv') # path

## DataSet Visual Representation!

In [5]:
# Display first 10 rows in Train dataset
display(Train.head(10))

,intercolumnar distance,upper margin,lower margin,exploitation,row number,modular ratio,interlinear spacing,weight,peak number,modular ratio,class
0,0.117948,-0.220579,0.367214,0.914608,0.261718,1.353010,1.352689,-0.386503,-0.185368,0.541155,A
1,0.809204,-0.094960,0.118265,0.987502,0.976743,-0.515608,-0.950086,0.800147,1.155435,0.244286,I
2,0.080916,0.014957,0.064919,0.346104,0.172340,0.107265,0.446679,0.319927,0.313536,-0.028184,A
3,-3.461768,-0.204876,-3.210528,-3.441837,-3.045274,-1.636779,-8.953175,3.273029,-3.895963,-5.460407,F
4,0.056229,-0.730905,0.441898,0.183695,0.261718,1.685209,0.522180,-0.591821,-0.154186,1.319049,A
5,-0.227680,-0.110662,0.196506,1.060099,0.261718,0.148790,0.484429,1.114909,1.872609,-0.005087,X
6,0.043885,0.572391,0.004460,-0.333100,0.261718,-0.889332,0.144676,0.653638,0.687713,-0.763198,G
7,0.204355,-0.134216,0.043581,-0.654873,0.261718,-0.100360,0.597681,-0.460903,0.625350,-0.282825,E
8,-0.128929,-0.511072,0.342319,0.170775,0.261718,1.643684,0.333428,-0.462980,-0.278912,1.416563,F
9,-0.215336,0.281897,0.107596,0.739220,0.082961,0.688613,-0.157328,-0.039337,0.594169,0.853769,E

In [56]:
# Display first 10 rows in Test dataset
display(Test.head(10))

   intercolumnar distance   upper margin  ...  modular ratio  class
0                 0.130292     -0.314793  ...       0.400605    NaN
1                -0.104241     -0.314793  ...      -1.312598    NaN
2                 0.019197     -0.040001  ...      -0.209421    NaN
3                -0.326430     -0.652394  ...      -3.113659    NaN
4                 0.031541     -0.346197  ...      -1.852354    NaN
5                -0.128929     -0.134216  ...      -0.063434    NaN
6                 0.278418     -0.361900  ...      -0.216835    NaN
7                -0.240024     -0.299090  ...       0.770999    NaN
8                -0.388150     -1.021399  ...       1.075849    NaN
9                -0.030178      0.391814  ...      -0.456274    NaN

[10 rows x 11 columns]

In [57]:
# display the General information of the Train dataset 
display(Train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8344 entries, 0 to 8343
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   intercolumnar distance   8344 non-null   float64
 1   upper margin             8344 non-null   float64
 2   lower margin             8344 non-null   float64
 3   exploitation             8344 non-null   float64
 4   row number               8344 non-null   float64
 5   modular ratio            8344 non-null   float64
 6   interlinear spacing      8344 non-null   float64
 7   weight                   8344 non-null   float64
 8   peak number              8344 non-null   float64
 9   modular ratio            8344 non-null   float64
 10  class                    8344 non-null   object
dtypes: float64(10), object(1)
memory usage: 717.2+ KB

None

In [58]:
# display the General information of the Test dataset 
display(Test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2086 entries, 0 to 2085
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   intercolumnar distance   2086 non-null   float64
 1   upper margin             2086 non-null   float64
 2   lower margin             2086 non-null   float64
 3   exploitation             2086 non-null   float64
 4   row number               2086 non-null   float64
 5   modular ratio            2086 non-null   float64
 6   interlinear spacing      2086 non-null   float64
 7   weight                   2086 non-null   float64
 8   peak number              2086 non-null   float64
 9   modular ratio            2086 non-null   float64
 10  class                    0 non-null      float64
dtypes: float64(11)
memory usage: 179.4 KB

None

## Split The Train DataSet into Training and Testing DataSet

In [59]:
# import the train_test_split function from the sklearn library
from sklearn.model_selection import train_test_split

In [60]:
# Apply the function and split the data 
x_train,x_test,y_train,y_test = train_test_split(Train.iloc[:,:10],
                                                 Train['class'],test_size = 0.25)

## DataSet Visual Representation!

In [61]:
# Display first 6 rows in x_train dataset
display(x_train.head(6))

      intercolumnar distance   upper margin  ...  peak number   modular ratio
4997                -0.351118     -0.314793  ...      2.870416       1.448678
6756                -0.104241     -0.456114  ...      0.064084       0.298824
2818                 0.117948     -0.220579  ...      0.562987       0.461158
4616                 0.599358     -2.426761  ...      2.184424      -0.691759
1996                -0.153617     -0.228430  ...      0.157628       0.863727
4206                -0.104241     -1.037102  ...      1.342524      -0.716014

[6 rows x 10 columns]

In [62]:
# Display first 6 rows in x_train dataset
display(x_test.head(6))

      intercolumnar distance   upper margin  ...  peak number   modular ratio
4002                 0.031541      0.446772  ...     -0.996086       0.067353
3634                -0.252367      0.093469  ...     -0.216549       1.159041
6995                 0.130292      0.533135  ...      0.438262      -0.873080
4716                -0.042522     -0.322644  ...     -0.621908      -0.615462
8022                 0.043885      0.407516  ...     -0.466001      -0.077176
5378                -0.128929     -0.040001  ...      1.997335      -0.534234

[6 rows x 10 columns]

In [63]:
# Display first 6 rows in x_train dataset
display(y_train.head(6))

4997    X
6756    F
2818    A
4616    I
1996    A
4206    X
Name: class, dtype: object

In [64]:
# for 1 hot encoding
y_train = pd.get_dummies(y_train,columns=['class'])
y_test = pd.get_dummies(y_test,columns=['class'])

In [65]:
# Display first 5 rows in x_train dataset
y_train.head()

      A  B  C  D  E  F  G  H  I  W  X  Y
4997  0  0  0  0  0  0  0  0  0  0  1  0
6756  0  0  0  0  0  1  0  0  0  0  0  0
2818  1  0  0  0  0  0  0  0  0  0  0  0
4616  0  0  0  0  0  0  0  0  1  0  0  0
1996  1  0  0  0  0  0  0  0  0  0  0  0

In [66]:
# Display first 5 rows in x_train dataset
y_test.head()

      A  B  C  D  E  F  G  H  I  W  X  Y
4002  0  0  0  0  0  1  0  0  0  0  0  0
3634  1  0  0  0  0  0  0  0  0  0  0  0
6995  0  0  0  0  0  0  1  0  0  0  0  0
4716  0  0  0  0  0  1  0  0  0  0  0  0
8022  1  0  0  0  0  0  0  0  0  0  0  0

In [67]:
display(y_train.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6258 entries, 4997 to 4449
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6258 non-null   uint8
 1   B       6258 non-null   uint8
 2   C       6258 non-null   uint8
 3   D       6258 non-null   uint8
 4   E       6258 non-null   uint8
 5   F       6258 non-null   uint8
 6   G       6258 non-null   uint8
 7   H       6258 non-null   uint8
 8   I       6258 non-null   uint8
 9   W       6258 non-null   uint8
 10  X       6258 non-null   uint8
 11  Y       6258 non-null   uint8
dtypes: uint8(12)
memory usage: 122.2 KB

None

## Create The Neural Networking Model and Fit it on The DataSet

In [68]:
# import keras and other layers
 
import keras 
from keras.layers import Dense, Dropout
from keras.models import Sequential

In [69]:
# model architecture

model=Sequential()

model.add(Dense(3600,activation='relu',input_shape=(10,)))
model.add(Dense(2700,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(2500,activation='relu'))
model.add(Dense(2000,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(2700,activation='relu'))
model.add(Dense(1800,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(900,activation='relu'))
model.add(Dense(800,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(600,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(400,activation='relu'))
model.add(Dense(300,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(250,activation='relu'))
model.add(Dense(12,activation='softmax'))

# model compilation

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

# fitting the model

model.fit(x_train,y_train,epochs=100)

Epoch 1/100
196/196 [==============================] - 3s 11ms/step - loss: 1.6871 - accuracy: 0.4436
Epoch 2/100
196/196 [==============================] - 2s 11ms/step - loss: 1.4012 - accuracy: 0.5268
Epoch 3/100
196/196 [==============================] - 2s 11ms/step - loss: 1.2984 - accuracy: 0.5630
Epoch 4/100
196/196 [==============================] - 2s 11ms/step - loss: 1.2726 - accuracy: 0.5668
Epoch 5/100
196/196 [==============================] - 2s 11ms/step - loss: 1.1877 - accuracy: 0.5880
Epoch 6/100
196/196 [==============================] - 2s 11ms/step - loss: 1.2705 - accuracy: 0.5689
Epoch 7/100
196/196 [==============================] - 2s 11ms/step - loss: 1.2470 - accuracy: 0.5735
Epoch 8/100
196/196 [==============================] - 2s 11ms/step - loss: 1.1866 - accuracy: 0.5927
Epoch 9/100
196/196 [==============================] - 2s 11ms/step - loss: 1.1051 - accuracy: 0.5983
Epoch 10/100
196/196 [==============================] - 2s 11ms/step - loss: 1.1474 - accuracy: 0.5872
Epoch 11/100
196/196 [==============================] - 2s 11ms/step - loss: 1.1617 - accuracy: 0.5663
Epoch 12/100
196/196 [==============================] - 2s 11ms/step - loss: 1.2363 - accuracy: 0.5622
Epoch 13/100
196/196 [==============================] - 2s 11ms/step - loss: 1.0922 - accuracy: 0.6010
Epoch 14/100
196/196 [==============================] - 2s 11ms/step - loss: 1.0696 - accuracy: 0.6037
Epoch 15/100
196/196 [==============================] - 2s 11ms/step - loss: 1.0307 - accuracy: 0.6205
Epoch 16/100
196/196 [==============================] - 2s 11ms/step - loss: 1.0274 - accuracy: 0.6125
Epoch 17/100
196/196 [==============================] - 2s 11ms/step - loss: 1.0946 - accuracy: 0.6072
Epoch 18/100
196/196 [==============================] - 2s 11ms/step - loss: 1.0288 - accuracy: 0.6123
Epoch 19/100
196/196 [==============================] - 2s 11ms/step - loss: 0.9750 - accuracy: 0.6238
Epoch 20/100
196/196 [==============================] - 2s 11ms/step - loss: 0.9198 - accuracy: 0.6531
Epoch 21/100
196/196 [==============================] - 2s 11ms/step - loss: 0.9096 - accuracy: 0.6702
Epoch 22/100
196/196 [==============================] - 2s 11ms/step - loss: 0.8686 - accuracy: 0.6692
Epoch 23/100
196/196 [==============================] - 2s 11ms/step - loss: 0.8526 - accuracy: 0.6879
Epoch 24/100
196/196 [==============================] - 2s 11ms/step - loss: 0.9228 - accuracy: 0.6793
Epoch 25/100
196/196 [==============================] - 2s 11ms/step - loss: 0.9014 - accuracy: 0.6764
Epoch 26/100
196/196 [==============================] - 2s 11ms/step - loss: 0.8596 - accuracy: 0.7061
Epoch 27/100
196/196 [==============================] - 2s 11ms/step - loss: 0.8281 - accuracy: 0.7089
Epoch 28/100
196/196 [==============================] - 2s 11ms/step - loss: 0.8227 - accuracy: 0.7207
Epoch 29/100
196/196 [==============================] - 2s 11ms/step - loss: 0.8002 - accuracy: 0.7320
Epoch 30/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7458 - accuracy: 0.7466
Epoch 31/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7001 - accuracy: 0.7581
Epoch 32/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7471 - accuracy: 0.7442
Epoch 33/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7769 - accuracy: 0.7430
Epoch 34/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7670 - accuracy: 0.7450
Epoch 35/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7951 - accuracy: 0.7478
Epoch 36/100
196/196 [==============================] - 2s 11ms/step - loss: 0.9017 - accuracy: 0.6970
Epoch 37/100
196/196 [==============================] - 2s 11ms/step - loss: 0.8116 - accuracy: 0.7394
Epoch 38/100
196/196 [==============================] - 2s 11ms/step - loss: 0.6851 - accuracy: 0.7721
Epoch 39/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7461 - accuracy: 0.7589
Epoch 40/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7678 - accuracy: 0.7464
Epoch 41/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7200 - accuracy: 0.7611
Epoch 42/100
196/196 [==============================] - 2s 11ms/step - loss: 0.6882 - accuracy: 0.7725
Epoch 43/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7005 - accuracy: 0.7709
Epoch 44/100
196/196 [==============================] - 2s 11ms/step - loss: 0.8019 - accuracy: 0.7632
Epoch 45/100
196/196 [==============================] - 2s 11ms/step - loss: 0.7222 - accuracy: 0.7669
Epoch 46/100
196/196 [==============================] - 2s 11ms/step - loss: 0.6830 - accuracy: 0.7705
Epoch 47/100
196/196 [==============================] - 2s 11ms/step - loss: 0.6720 - accuracy: 0.7784
Epoch 48/100
196/196 [==============================] - 2s 11ms/step - loss: 0.8237 - accuracy: 0.7470
Epoch 49/100
196/196 [==============================] - 2s 11ms/step - loss: 0.6642 - accuracy: 0.7803
Epoch 50/100
196/196 [==============================] - 2s 11ms/step - loss: 0.6184 - accuracy: 0.7955
Epoch 51/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5793 - accuracy: 0.8039
Epoch 52/100
196/196 [==============================] - 2s 11ms/step - loss: 0.6021 - accuracy: 0.8011
Epoch 53/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5611 - accuracy: 0.8118
Epoch 54/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5894 - accuracy: 0.8076
Epoch 55/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5859 - accuracy: 0.8150
Epoch 56/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5585 - accuracy: 0.8207
Epoch 57/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5509 - accuracy: 0.8186
Epoch 58/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5073 - accuracy: 0.8345
Epoch 59/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5809 - accuracy: 0.8198
Epoch 60/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5445 - accuracy: 0.8236
Epoch 61/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5466 - accuracy: 0.8229
Epoch 62/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5574 - accuracy: 0.8245
Epoch 63/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5113 - accuracy: 0.8378
Epoch 64/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5809 - accuracy: 0.8159
Epoch 65/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5735 - accuracy: 0.8154
Epoch 66/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4981 - accuracy: 0.8391
Epoch 67/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4885 - accuracy: 0.8447
Epoch 68/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5007 - accuracy: 0.8418
Epoch 69/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4933 - accuracy: 0.8416
Epoch 70/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4759 - accuracy: 0.8415
Epoch 71/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5729 - accuracy: 0.8287
Epoch 72/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5559 - accuracy: 0.8268
Epoch 73/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5369 - accuracy: 0.8284
Epoch 74/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4836 - accuracy: 0.8439
Epoch 75/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4701 - accuracy: 0.8452
Epoch 76/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5629 - accuracy: 0.8289
Epoch 77/100
196/196 [==============================] - 2s 11ms/step - loss: 0.6151 - accuracy: 0.8418
Epoch 78/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4798 - accuracy: 0.8539
Epoch 79/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4993 - accuracy: 0.8440
Epoch 80/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4535 - accuracy: 0.8539
Epoch 81/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5239 - accuracy: 0.8349
Epoch 82/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5134 - accuracy: 0.8397
Epoch 83/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5655 - accuracy: 0.8337
Epoch 84/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4868 - accuracy: 0.8516
Epoch 85/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4925 - accuracy: 0.8477
Epoch 86/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5582 - accuracy: 0.8322
Epoch 87/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4801 - accuracy: 0.8466
Epoch 88/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5556 - accuracy: 0.8453
Epoch 89/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4955 - accuracy: 0.8440
Epoch 90/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4729 - accuracy: 0.8546
Epoch 91/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4481 - accuracy: 0.8584
Epoch 92/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4369 - accuracy: 0.8656
Epoch 93/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4298 - accuracy: 0.8691
Epoch 94/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4024 - accuracy: 0.8712
Epoch 95/100
196/196 [==============================] - 2s 11ms/step - loss: 0.5678 - accuracy: 0.8648
Epoch 96/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4517 - accuracy: 0.8623
Epoch 97/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4280 - accuracy: 0.8694
Epoch 98/100
196/196 [==============================] - 2s 11ms/step - loss: 0.3735 - accuracy: 0.8826
Epoch 99/100
196/196 [==============================] - 2s 11ms/step - loss: 0.4322 - accuracy: 0.8659
Epoch 100/100
196/196 [==============================] - 2s 11ms/step - loss: 0.3796 - accuracy: 0.8794

## Check The Models Accuracy

In [70]:
# Predict on x_test dataset 
prediction = model.predict(x_test)
prediction.shape

(2086, 12)

In [71]:
# get the predicted class value
predicted_class = np.argmax(prediction, axis = -1)
actual_class = np.argmax(np.array(y_test), axis = -1)

In [82]:
predicted_class

array([5, 0, 6, ..., 7, 0, 6])

In [83]:
actual_class

array([5, 0, 6, ..., 7, 0, 6])

In [84]:
# get the accuracy of the model
per = len(list(x_test))
total = len(list(x_test))
for i in range(per):
    if predicted_class[i] != actual_class[i]:
        per -= 1
print(round(per/total,2))

1.0

## Now Predict The Class of Test DataSet Using The Model

In [86]:
# Now Predict the Test Datset "class" field
result = model.predict(Test.iloc[:,:10])
result.shape

(2086, 12)

In [87]:
# get the class value
result = np.argmax(result, axis = -1)

In [88]:
# Index 
classes = range(12)

# Lables Name
lables = ['A','B','C','D','E','F','G','H','I','W','X','Y']

# Zip the index and there corresponding lable name to make a dictionary
class_lable = dict(zip(classes, lables))

In [89]:
# now replace the index value with it's class value
final_result = []
for n in range(len(result)):
    final_result.append(class_lable[result[n]])

In [91]:
# Save the prediction as result.csv file in the local directory
final_result = pd.DataFrame(final_result)
final_result.to_csv('result.csv')